app.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('en-fr', {
        /*复用较多的东西 */
        "Me": "Moi",
        "Enter": "Entrer",
        "Add_Folder": " Ajouter un dossier",
        "Move_to_Folder": " Déplacer vers un dossier",
        "Rename_Folder": " Renommer le dossier",
        "Delete_Folder": " Supprimer le dossier",
        "New_Folder": " Créer un nouveau dossier",
        "Rename": " Renommer ",
        "Create": " Créer",
        "Folder_Name": " Nom du dossier",
        "Are you sure delete the folder?": " Êtes-vous sûr de vouloir supprimer le fichier?",
        "Tody": " Aujourd'hui",
        "Success": " Accompli ",
        "Cancel": "Annuler",
        "Submit": " Soumettre ",
        "Apply": " Appliquer",
        "Confirm": " Confirmer",
        "confirm": " Confirmer",
        "Default": " par défaut ",
        "default": " par défaut ",
        "YES": " Oui",
        "NO": " Non",
        "All": " Tous",
        "Half Day": " Une demi-journée ",
        "Search": " Rechercher ",
        "Save": " Enregistrer ",
        "New": " Nouveau",
        "Current": " Courant ",
        "Succeed": " Accomplir ",
        "Refresh": " Rafraîchir ",
        "Delete": " Supprimer ",
        "Filter": " Filtrer ",
        "Effect": " Effet ",
        "Notice": " Attention ",
        "Persist": " Persister ",
        "min": " Minute ",
        "Edit": "Éditer ",
        "px/s": " px/s ",
        "px": "px",
        "s": "s",
        "ms": "ms",
        "Width": " Largeur ",
        "W": "L",
        "H": "H",
        "Height": " Hauteur ",
        "Name": " Nom ",
        "Scale": " Zoom ",
        "Description": " Description ",
        "Display_Items_per_Page": " Nombre des articles par page ",
        "Previous": " Page précédente ",
        "Next": " Page suivante ",
        "Hint": " Hint",
        "Warm_Prompt": " Attention ",
        "Illegal_value,please_input_number!": " Valeur invalide, veuillez entrer le nombre!",
        "Illegal_value,please_input_0.5_to_3!": " Valeur invalide, veuillez entrer un nombre de 0.5 à 3!",
        "Invalid_content_or_content_name!": " Contenu invalide ou nom de contenu invalide ",
        "Confirm": " Confirmer ",
        "Num": " Nombre ",
        "Replace": " Remplacer ",
        "Setting": " Réglages ",
        "Display": " Afficher ",
        "Year": " Année ",
        "Month": " Mois ",
        "Day": " Jour ",
        "Week": " Semaine ",
        "Device_time": " Temps de l'équipement ",
        "Time": " Temps ",
        "Hour": " Heure ",
        "Minute": " Minute ",
        "Second": " seconde ",
        "d": "J",
        "h": "H",
        "m": "M",
        "s": "S",
        "Operation": " En cours d'exécution ",
        "draft,pending": " Brouillon pendant ",
        "start_playing": " Commencer l'opération ",
        "Storage_Space": " Espace de stockage ",
        "storage": " Stockage ",
        "The_operation_is_unrecoverable,_are_you_sure_to_continue?": " L'opération est irrécupérable, est-ce que vous êtes sûr de continuer? ",
        "Invalid_Input": " entrée invalide ",
        "invalid_program": " programme invalide ",
        "A_cautious_operation!_Are_you_sure_to_upgrade?": " C’est une opération prudente．Êce－que vous êtes sûr de continuer？",
        "You_have_no_permission_to_do_this": " Vous n'avez pas la permission de le faire ",
        "Download_terminal_log_for_a_week": " Télécharger le journal des terminaux pour cette semaine ",
        "Search_Terminal": " Rechercher le terminal ",
        "No_corresponding_terminal_found": " Aucun terminal correspondant n'est trouvé",
        /*侧边栏*/
        "Terminal_": " Terminal ",
        "Terminal": " Terminal ",
        "Media_": " Matériel ",
        "No-Media": " Pas de matériel ",
        "Only_Support_Chinese,Alphanumeric and Numbers": " Le nom du programme ne prend en charge que les caractères chinois, les lettres et les chiffres. ",

        "Contents_": " Contenu ",
        "Edit_Contents": " Editer le contenu ",
        "Log_": " Journal",
        "Map_Monitoring": " Surveillance de la carte ",
        "Account_": " Compte ",
        "account": " Compte ",
        "Account_Info": " Informations sur le compte ",
        "account_changed": " Changer le compte ",
        "Sign_Up": " S'inscrire ",
        "Unblock_IP": " Débloquer IP ",
        "Fold": " Plier ",
        "New_Terminal": " Nouveau terminal ",
        'E-mail already exists': " L'e-mail déjà existe ",
        "Contents": " Contenus ",
        "Update_Time": " Heure de mise à jour ",
        "NO_DATA": " Aucune donnée ",
        /*关于系统，个人设置*/
        "Personal_Setting": " Paramètres personnels ",
        "Log_Out": " Déconnexion ",
        "About": "À propos de ",
        "About_System": " A propos de ce système ",
        "Server_Version": " Version du serveur ",
        "C_Series_Internet_Management_Center": " Centre de gestion Internet de C-série ",
        "We_advise_visiting_our_Web_App_via_chrome_browser": " Nous vous recommandons d'utiliser Google Chrome pour accéder à notre application Web",
        "Also_you_can_install_our_chrome-app_for_better_experience": " Vous pouvez installer notre application de Google pour obtenir une meilleure expérience ",
        "How_to_install_chrome-app": " Manuel pour installer Google Apps ",
        "C-CLOUD_Manual": " Manuel d'instructions de C-CLOUD ",
        /*终端列表*/
        "Terminal_View": " Vue du terminal ",
        "Viewing_Type": " Type de vue ",
        "Grid": " Grille ",
        "List": " Liste ",
        "Card": " Carte ",
        "Search_Terminal_Group": " Veuillez rechercher le groupe des terminaux ",
        "Group": " Groupe ",
        "Terminal_Group": "Groupe des terminaux",
        "All_Groups": " Tous les groupes ",
        "New_Group": " Nouveau groupe des terminaux ",
        "Select_a_device_or_a_group": " Veuillez sélectionner un groupe des terminaux ou un équipement ",
        "Group_Name": " Nom du groupe des terminaux ",
        "Group_Description": " Description du groupe ",
        "No_terminal_in_this_group": " Ce groupe n'a aucun terminal ",
        "NO_Terminal": " Aucun terminal ",
        "You_have_no_terminal": " Vous n'avez pas de terminal ",
        "Click_here": " Cliquez ici ",
        "Create_a_terminal": " Créer un terminal ",
        "Device_is_offline_and_current_info_was_uploaded_last_time": " L'équipement est hors ligne! Les informations affichées sont les dernières informations rapportées. ",
        "Offline_time": " La dernière fois que l'équipement s'est connecté au serveur",
        "Last_Online_Time": " La dernière fois que l'équipement est on ligne ",
        "Last_Online": " La dernière fois que l'équipement est on ligne ",
        "This_terminal_is_uninitialized_install_terminal_and_have_it_connected_to_the_server": " Le terminal n'est pas initialisé. Installez le terminal et connectez-le au serveur ",
        "This_terminal_is_uninitialized_please_install_terminal_and_have_it_connected_to_the_server": " Le terminal n'est pas initialisé. Installez le terminal et connectez-le au serveur ",
        "Not_initialized": " Le terminal n'est pas initialisé",
        "The_upgrade_package_version_number_is_lower_than_the_device_version_number": " Le numéro de version du package de mise à jour est inférieur au numéro de version de l'équipement.  ",
        "Running_Time": " Temps d'exécution ",
        "Up_Time": " Temps d'exécution ",
        "runtime": " Temps d'exécution ",
        "Days": " Journées ",
        "Hours": " Heures ",
        "Minutes": " Minutes ",
        "Seconds": " Secondes ",
        "Control": " Contrôle ",
        "Brightness": " Luminosité",
        "Colortemp": " Température de couleur ",
        "Volume": " Volume ",
        "Brightness_Control": " Réglage de la luminosité",
        "Colortemp_Control": " Réglage de la température de couleur ",
        "Volume_Control": " Réglage du volume ",
        "Terminal_Status": "État de l'équipement ",
        "Running": " En cours d'exécution ",
        "Sleeping": " Endormi ",
        "Offline": " Hors ligne ",
        "Offline_alarm": " Alarme d'hors ligne ",
        "Mailing_List": " Liste d'e-mail ",
        'Don\'t_send_mail_offline': " N'envoyez pas d'e-mail pour hors ligne ",
        "Add_an_Email": " Ajouter une addresse d'e-mail ",
        "Open_to_send_mail": " Activer l'envoi d'e-mail' ",
        "Trun_off_sending_mail": " Désactiver l'envoi d'e-mail ",
        "E-mail_format_is_incorrect!": " Le format d'e-mail est incorrect ",
        "Rebooting": " Redémarrage ",
        "Sleep": " Endormir",
        "Wakeup": " Réveiller ",
        "Reboot": " Redémarrer",
        "Reboot_Later": " Redémarrer plus tard",
        "Reboot_Now": " Redémarrer maintenant ",
        "Timing": " Horloge ",
        "Playing": " Jouer ",
        "Screen_Shot": " Capture d'écran ",
        "Camera_Shot": " Capture d'écran de la caméra ",
        "Complete": " Accomplir ",
        "Confirm": ' Confirmer ',
        "Screenshots_Complete": " Capture d'écran accomplie ",
        "The_firmware_version_of_this_device_doesn`t_support_content_report": " La version de  l'équipement ne prend pas en charge les rapports de contenu ",
        "Confirm_that_the_terminal_has_camera": " Confirmer si le terminal a une caméra ",
        "Must_contain_at_least_one_number_and_one_uppercase_and_lowercase_letter, and_at_least_8_or_more_characters": "  Il faut contenir au moins un chiffre, une lettre majuscule et une lettre minuscule, et une longueur minimale de 8 caractères.",
        "Terminal_Content": " Contenu du terminal ",
        "New_Text": " Nouveau texte ",
        "Storage": " Stockage",
        "Available": " Disponible ",
        "Not_Available": " Non disponible ",
        "Total": " Total ",
        "Used": " Utilisé ",
        "used": " Utilisé ",
        "Max:": " Maximum:",
        "Min:": " Minimum ",
        "Auto_Brightness": " Luminosité automatique ",
        "Master Brightness": " Luminosité manuelle ",
        "Auto": " Automatique ",
        "Change_brightness_automatically_when_lightning_changes": " Changer automatiquement la luminosité lorsque la luminosité externe change ",
        "Please_enter_a_positive_integer_from_0-100": " Entrer un entier positif de 0-100 ",
        /*同步异步切换*/
        "Switch_Signal_Source": " Commutation de source de signal ",
        "Signal_Source": " Source de signal ",
        "Priority": " Priorité",
        "Async_Signal": " Signal asynchrone ",
        "Sync_Signal": " Signal synchrone ",
        "Using": " En cours d'utilisation ",
        "Only_C6_and_C7_have_the_function": " Cette fonction est uniquement disponible pour C6 et C7 ",
        "Only_C6、C7_and_C8_have_the_function": " Cette fonction est uniquement disponible pour C6, C7 et C8 ",
        "sync": " Synchrone ",
        "async": " Asynchrone ",
        "Switch": " Commuter ",
        "Bright": " La luminosité",
        /*新建终端组*/

        "Program_is_empty": " Le contenu est vide ",
        "Select_is_empty": " Le contenu sélectioné est vide ",
        "Bulk_Delete": " Supprimer en gros ",
        "Select_a_group": " Veuillez sélectionner un groupe des terminaux ",
        "New_Group": " Nouveau groupe des terminaux ",
        "Enter_group_name": " Veuillez entrer le nom du groupe des terminaux ",
        "enter_group_name": " Veuillez entrer le nom du groupe des terminaux ",
        "Enter_group_name_within_2_to_20_characters": " Veuillez saisir un nom de groupe des terminaux de 2 à 20 caractères ",
        "Enter_group_description": " Veuillez saisir une description du groupe des terminaux ",
        "Enter_group_description_within_2_to_200_characters": " Veuillez saisir une description de groupe des terminaux de 2 à 200 caractères ",
        "Free_Number": " Numéro gratuit ",
        "Select_Parent": " Sélectionner le groupe de terminaux parent ",
        "Invalid_Content_Name": " Le nom du programme est illégal ",
        "The_Terminal_Group_You_Search_Does_Not_Exist": " Le groupe de terminaux que vous recherchez n'existe pas ",
        /*终端列表*/
        "Terminal_Name": " Nom du terminal ",
        "Version": " Version du terminal ",
        "uninitialized": " Non initialisé",
        "Uninitialized": " Non initialisé",
        "Belong_to": " Appartenir à",
        "Update": " Mise à jour ",
        "Upgrade": " Mise à niveau ",
        "Upgrade_Status": " Statut de mise à niveau ",
        "Last_Upgraded_Time": " Dernière mise à jour ",
        "downloading": " Téléchargement ",
        "downloaded": " Téléchargement terminé",
        "Download_full_information": " Télécharger l'information complète ",
        "upgrading": " Mise à niveau ",
        "successful": " Le succès ",
        "failed": "Échec ",
        "Failed": "Échec ",
        "No_Info": " Non téléchargé",
        "Progress": " Les progrès ",
        "Total_Progress": " Progrès globaux ",
        "Publishing_Progress": " Progression de la publication ",
        "Downloading_Progress": " Progression du téléchargement ",
        "Contents_Downloading": " Téléchargement du Contenu ",
        "Contents_Downloaded": " Téléchargement du Contenu ",
        "Total_Progress": " Progrès globaux ",
        "Single_content_dowloading_progress": " Progression du téléchargement de contenu unique ",
        "The_detailed_information": " Détails du Contenu ",
        "Details": " Détails ",
        "Online:": " En ligne:",
        "Offline:": " Hors ligne:",
        "Number_of_online_terminals": " Nombre de terminaux en ligne ",
        "Number_of_offline_terminals": " Nombre de terminaux hors ligne ",
        /*新建终端*/
        "Terminal_Description": " Description du terminal ",
        "New_LED_Terminal": " Nouveau terminal à LED ",
        "LED_Terminal_ID": " Informations sur le terminal LED ",
        "Terminal_Info": " Informations sur le terminal ",
        "Edit_Terminal": " Modifier le terminal ",
        "Enter_terminal_name": " Entrez le nom du terminal ",
        "Input_Location": " Emplacement d'entrée ",
        "Enter_terminal_name_within_2_to_20_characters": " Veuillez saisir un nom de terminal de 2 à 20 caractères ",
        "Enter_terminal_description": " Entrez la description du terminal ",
        "Enter_terminal_description_within_2_to_100_characters": " Veuillez saisir une description de terminal de 2 à 100 caractères ",
        "Enter_terminal_description_within_0_to_200_characters": " Veuillez saisir une description de terminal de 0 à 200 caractères.",
        "Free_Number": " Numéro gratuit ",
        "Select_Group": " Sélectionnez le groupe de terminaux ",
        "Sign_up_terminal_account": " Demander un compte de connexion au terminal ",
        "User_Name": " Nom d'utilisateur ",
        "Report_Log": " Journal de rapport ",
        "Clock_Style": " Style d'horloge ",
        "Timer_Style": " Style de minuterie ",
        "Weather_Style": " Style météo ",
        "Environment_Style": " Style de l'environnement ",
        "Content_Report": " Rapport de contenu ",
        "Outline/Shadow": " Contour / Ombre ",
        "Outline": " Contour ",
        "Text_Outline": " Contour du texte ",
        "Text_Shadow": " Ombre du texte ",
        "Shadow": " Ombre ",
        "Dx": " Décalage d'axe X ",
        "Dy": " Décalage d'axe Y ",
        "Blur": " Brouiller ",
        "Require_Player_Ver": " Version requise ",
        "Play_Duration": " Durée de jeu ",
        "Play_Times": " Temps de jeu ",
        "No_User_Log": " Aucun journal d'utilisateur ",
        "Log_in": " Connexion ",
        "Remember_Me": " Souviens-toi de moi ",
        "Incorrect_username_or_password": " identifiant ou mot de passe incorrect ",
        "Account": " Compte ",
        "Account changed": " Compte changé",
        "Account changed.": " Compte changé",
        "Enter_account": " Entrer compte ",
        "Enter_account_within_2_to_100_characters": " Entrez un compte de longueur 2 100 ",
        "The_account_already_exists": " Le compte existe déjà！",
        "Password": " Mot de passe ",
        "Enter_password": " Entrer le mot de passe ",
        "Enter_password_within_6_to_100_characters": " Veuillez saisir un mot de passe de 6 à 100 caractères ",
        "Reenter_password": " Réentrez le mot de passe ",
        "The_two_passwords_you_entered_did_not_match": " Les deux mots de passe que vous avez entrés ne correspondaient pas ",
        "How_to_let_terminal_connect_internet_server": " Comment connecter le terminal au serveur d'internet? ",
        "How_to_new_terminal_group": " Comment créer un nouveau groupe des terminaux ",
        /*节目计费*/
        "The_end_time_must_be_greater_than_the_start_time": " L'heure de fin doit être supérieure à l'heure de début ",
        /*新建用户*/
        "Email": " Email ",
        "Wifi_speed": " Vitesse de wifi ",
        "Line_Type": " Type de réseau ",
        "Latitude": " Latitude ",
        "Longitude": " Longitude ",
        "Group": " Groupe des terminaux ",
        "Enter_an_available_email": " Entrer une adresse d'email disponible ",
        "The_email_has_been_registered": " L'adresse d'email a été enregistrée ",
        "Bind_Terminal_Group": "Lier un groupe des terminaux ",
        "Why_bind_terminal_group": " Pourquoi voulez-vous lier un groupe des terminaux? ",
        "Role": " Rôle ",
        "Administrator": " Administrateur ",
        "Contents_Editor": " Producteur de programme ",
        "Sign_Up_": " Inscrire ",
        "Sign_Up_Date": " Date d'inscription ",
        "Subsidiary_Account": " Utilisateur subordonné",
        "Sign_Up_Subsidiary_Account": " Inscription les utilisateurs subordonnés ",
        "Sign_Up_Successful": " Inscription réussie ",
        "Invitor": " Personne invitée ",
        "Monitor": " Moniteur ",
        "Username_is_illegal": " Le nom d'utilisateur est illégal ",
        /*终端定时管理*/
        "Timing_Management": " Gestion du temps ",
        "Everyday": " Tous les jours ",
        "Select": " Sélectionner ",
        "Time": " Temps ",
        "Sleep_Schedule": " Horaire de sommeil ",
        "Wakeup_Schedule": " Horaire de réveil ",
        "Reboot_Schedule": " Horaire de redémarrage ",
        "Total": " Total ",
        "total": " Total ",
        "Terminal_don`t_have_this_function": " Le terminal sélectionné n'a pas cette fonction ",
        /*屏幕截图*/
        "Screen_Shot123": " Capture d'écran ",
        "Refresh": " Mettre à jour ",
        "Refresh_Time": " Temps de la mise à jour ",
        "No_camera_available": " Le terminal n'a pas de caméra ",
        "Timed_out,_please_try_again!": " Timeout, s'il vous plaît essayez à nouveau!",
        /*设置时间*/
        "Terminal_Date": " Date du terminal ",
        "Terminal_Time": " Heure du terminal ",
        "Set_Terminal_Time": " Définir l'heure du terminal ",
        "Set_Terminal_Date": " Définir la date du terminal ",
        "Terminal_Timezone": " Fuseau horaire du terminal ",
        "Date": " Date ",
        "Timezone": " Fuseau horaire ",
        "Locale": " Langue actuelle ",
        "Locale_setting": " Réglage de la localisation ",
        "Synchronized_with_Internet": " Synchroniser avec Internet ",
        /*终端节目管理*/
        "Terminal_Contents_Management": " Gestion du contenu du terminal ",
        "Switch_Contents": " Changer le contenu ",
        "Contents_Name": " Nom du contenu ",
        "Size": " Taille ",
        "Source": " Source ",
        "Delete": " Supprimer ",
        "Clean": " Vider",
        "Switching...": " Sélection...",
        "Play": " Jouer ",
        "Delete_All": " Supprimer tout ",
        "Clear_Cache": " Vider le cache ",
        "Cache_Being_Clear": " Le cache est effacé",
        "Cache_Being_Clear": " Le cache est effacé",
        "Internet_Contents": " Contenu Internet ",
        "Cache_Files": " Fichiers de cache ",
        "Select_upgrade_file": " Veuillez sélectionner un fichier de mise à niveau ",
        /*发布单行\多行文本*/
        "Length_of_1_-_512": " Limite de 1 à 512 caractères ",
        "Length_of_1_-_1000": " Limite de 1 à 1000 caractères",
        "Single_Line_Text_Uploading": " Envoi de texte sur une seule ligne ",
        "Single_line_text": " Une seule ligne de texte ",
        "Multi_line_text": " Texte multiligne ",
        "Enter_single_line_text_within_1_to_512_characters": " Veuillez entrer une seule ligne de texte de 1 à 512 caractères ",
        "Enter_multi_line_text_within_1_to_1000_characters": " Veuillez saisir un texte multiligne de 1 à 1000 caractères. ",
        "Range of 8 - 4096": " Entrez un entier compris entre 8 et 4096 ",
        "Range of 8 - 1536": " Entrez un entier compris entre 8 et 1536",
        "Range of -4096 - 4096": " Entrez un entier compris entre -4096 et 4096 ",
        "Range of 1 - 4096": " Entrez un entier compris entre 1 et 4096 ",
        "Range of -1536 - 1536": " Entrez un entier compris entre -1536 et 1536 ",
        "Range of 1 - 1536": " Entrez un entier compris entre 1 et 1536 ",
        "Range of 1 - 512": " Entrez un entier compris entre 1 et 512 ",
        "Range of 0 - 512": " Entrez un entier compris entre 0 et 512 ",
        "Range of 1 - 300": " Entrez un entier compris entre 1 et 300 ",
        "Range of 1 - 86400": " Entrez un entier compris entre 1 et 86400 ",
        "Range of 6 - 256": " Entrez un entier compris entre 6 et 256 ",
        "Enter_url": " Entrer l'URL ",
        "Font_Size": " Taille de la police ",
        "Font": " Glyphe ",
        "Bold": " Audacieux ",
        "Italic": " Italique ",
        "Underline": " Souligner ",
        "Font_Color": " Couleur de la police ",
        "Background": " Couleur de fond ",
        "Black_background_is_rendered_transparent_in_the_player": " Fond noir montre la transparence pendant la lecture ",
        "White": " Blanc ",
        "Black": " Noir ",
        "Red": " Rouge ",
        "Green": " Vert ",
        "Blue": " Bleu ",
        "Pages": " Des pages ",
        "Page_Duration": " Durée de la page ",
        "Move_Left": " Décalage gauche continu ",
        "Move_Top": " Mouvement ascendant continu ",
        "Head_Close_To_Tail": " Bout à bout ",
        "Scroll_Speed": " Vitesse de défilement ",
        "Points": " Point ",
        "Pixel": " Pixel ",
        "Play_Area": " Aire de jeux ",
        /*素材列表*/
        "Display_Type": " Type d'affichage ",
        "Display_Quantity": " Quantité affichée ",
        "All_File": " Tous les fichiers ",
        "Video": " Vidéo ",
        "Image": " Image ",
        "Click_Picture_To_Cut": " Cliquez sur l'image pour couper ",
        "Cancel_Crop": " Annuler le recadrage ",
        "Crop": " recadrage ",
        "Crop_Preivew": " Aperçu de la culture ",
        "Done": " Terminé",
        "TXT": "TXT",
        "Upgrade_File": " Fichier de mise à niveau ",
        "Bulk_Delete": " Suppression par lots ",
        "Bulk_Selection": " Sélection par lots ",
        "Cancel_Bulk_Delete": " Annuler la suppression en masse ",
        "Cancel_Bulk_Selection": " Annuler la sélection du lot ",
        "Select_All": " Sélectionner tout ",
        "Cancel_All": " Tout annuler ",
        "Type": " Type ",
        "Uploader": " Uploader ",
        "Download_the_file": " Télécharger le fichier ",
        "Specific_Uploader": " Limiter uploader ",
        "Uploader_Account": " Compte téléchargeur ",
        "Search_File_Name": " Nom du fichier de recherche ",
        "Upload_Date": " Date de dépôt ",
        "Specific_Date": " Date restreinte ",
        "Specific_Upload_Date": " Date de télécharger spécifique	",
        "File_Name": " Nom du fichier ",
        "Select": " Sélectionner ",
        "Unable_to_delete": " Impossible de supprimer ",
        "It_can_not_be_deleted": " Ce matériel ne peut pas être supprimé",
        "is_used_by_following_contents": " Ces spectacles utilisent le matériel ",
        /*素材上传*/
        "Loading": " Chargement ",
        "Load_Success": " Chargé avec succès ",
        "Load_Fail": " Chargement échoué",
        "Material": " Matériel ",
        "Material_Upload": " Téléchargement de matériel ",
        "File_Upload": " Téléchargement de fichier ",
        "Select_Or_Drag_Media": " Sélectionner ou faire glisser des matériel ",
        "Drag_Drop_Local_Below": " Faites glisser les médias locaux vers le bas ",
        "Uploaded_Quantity": " Quantité téléchargée ",
        "Upload_All": " Télécharger tout ",
        "Pause_All": " Tout suspendu ",
        "Remove_All": " Supprimer tout ",
        "Confirm_Upload": " Confirmer l'envoi ",
        "Uploading": " Téléchargement ",
        "Upload_Successfully": " Téléchargement réussi ",
        "Upload": " Téléchargement ",
        "Pause": " Suspendre ",
        "Remove": " Enlever ",
        "Actions": " actes ",
        "Upload_file": " Téléverser un fichier ",
        "Files_Already_Exist": " Les fichiers existent déjà",
        "Click_the_top_left_button_to_select_or_drag_files": " Cliquez sur le bouton en haut à gauche pour sélectionner ou faire glisser des fichiers ",
        "Terminal_only_supports_images(exclude_gif),_video_and_zip_upgrade_package_so_far": " Le terminal ne prend actuellement en charge que la vidéo, les images (à l’exclusion de gif) et les packages de mise à niveau zip ",
        /*" It is recommended to convert the video to MP4 ": " Recommander la conversion de la vidéo en MP4 ",*/
        "Max_size_of_a_Video": " Support vidéo maximum ",
        "Max_size_of_an_Image": " Support image maximum ",
        "Max_Resolution": " Résolution maximale ",
        "File_Size_Exceeds_Limit!": " La taille du fichier dépasse la limite!",
        "File_Duration_Exceeds_Limit!": " La résolution du fichier dépasse la limite!",
        "Unsupported_file_type": " Ce type de fichier n'est pas supporté",
        "The_image_size_exceeds_10M": " La taille de l'image dépasse 10M ",
        "The_file_size_exceeds_512M": " La taille de l'image dépasse 512M ",
        "The_zip_file_is_not_an_upgrade_package": " Ce fichier zip n'est pas un package de mise à niveau ",
        "Transcoding_error_!": " Erreur de transcodage ",
        "Uploading_or_transcoding,_are_you_sure_to_leave_?": " Chargement ou transcodage, êtes-vous sûr de partir?",
        "Uploading_or_transcoding,_please_try_again_later_!": " Téléchargement ou transcodage, veuillez réessayer plus tard!",
        "Files_is_uploading_or_transcoding, still_leave_this_page_?": " Le fichier est en cours de téléchargement ou de transcodage, êtes-vous sûr de partir?",
        "Up_to_10_medias,_the_excess_will_be_automatically_ignored!": " Téléchargez jusqu'à 10 clips à la fois, et l'excédent sera ignoré!",
        /*素材选择模态框*/
        "Select_the_material": " Veuillez sélectionner un matériau ",
        "Media_Materials": " Fichier multimédia du programme ",
        /*新建节目*/
        "Program": " programme ",
        "SimHei": " SimHei ",
        "KaiTi": " KaiTi ",
        "SimSun": " SimSun ",
        "LiSu": " LiSu ",
        "FangSong": " FangSong ",
        "New_Program123214": " Nouveau spectacle ",
        "Recover": " Récupération ",
        "You_have_uncommitted_Contents,Do_you_want_recover?": " Avez-vous des programmes non soumis, récupérez-vous?",
        "The_contents_has_not_been_submitted_yet, still_leave?": " Votre programme modifié n'a pas été soumis, êtes-vous sûr de vouloir partir?",
        "New_Program": " Nouveau spectacle ",
        "Submit_Edit": " Soumettre l'éditeur ",
        "New_Contents": " Nouveau contenu ",
        "Submit_Contents": " Soumettre contenu ",
        "Save_As_And_Publish": " Enregistrer sous et publier ",
        "Save_Modification": " Enregistrer ce changement ",
        "Save_As_Template": " Enregistrer comme modèle ",
        "Load_Template": " Chargement du gabarit ",
        "Enter_contents_name": " Entrez le nom du contenu ",
        "Template_can_not_be_published_to_terminal": " Le modèle ne peut pas être publié sur le terminal ",
        "If_you_just_want_to_submit_modification_of_template,plase_click": " Si vous souhaitez uniquement soumettre un modèle modifié, veuillez cliquer sur ",
        "Undo": " Annuler ",
        "Undo": " Annuler ",
        "Redo": " Récupération ",
        "Add": " Ajouter ",
        "Move_Up": " Déplacer vers le haut ",
        "Move_Down": " Descendre ",
        "Contents_Name": " Contenu Nom ",
        "Contents_Width": " Contenu Largeur ",
        "Contents_Height": " Contenu Hauteur ",
        "Play_Order": " Ordre de jeu ",
        "Preview_Window_Scale": " Facteur de zoom de la fenêtre d'aperçu ",
        "Allows_windows_be_out_of_bounds": " Autoriser la fenêtre à glisser hors de la bordure ",
        "Drop_Zone": " Zone de glissement ",
        "Window_Name": " Nom de la fenêtre ",
        "Layer": " Couche ",
        "Display_Layer": " Couche d'affichage ",
        "Maximize": " Maximiser ",
        "Border": " Frontière ",
        "top": " Top ",
        "bottom": " bas ",
        "Enter_a_Contents_Name_within_4_to_20_characters": " Veuillez entrer un nom de contenu de 4 à 20 caractères. ",
        "The_contents_is_not_created_on_the_web_for_which_can_not_be_edited": " L'émission n'a pas été créée sur le Web et ne peut pas être modifiée",
        "The_contents_version_is_old,_recreate": " La version du programme est plus ancienne, veuillez recréer ",
        "Add_new_page": " Ajouter une nouvelle page ",
        "Contents_Page": " contenu page",
        "Page_": "Page",
        "Add_File_Window": " Fenêtre Ajouter un fichier ",
        "Add_Sync_Play_Window": " Ajouter une fenêtre de lecture synchronisée ",
        "File_Window": " Fenêtre de lecture de fichier ",
        "Add_Web_Window": " Ajouter fenêtre Web ",
        "Resource_invalid!": " Le fichier est illégal ",
        "Rss_Window": " Fenêtre Rss ",
        "Add_Rss_Window": " Ajouter fenêtre Rss ",
        "12 Hours": "12 heures ",
        "24 Hours": "24 heures ",
        "AM/PM": " Matin / Après midi ",
        "Rss_Feed": "Chemin d'agrégation RSS",
        "Channel_Image": " Jouer image ",
        "Color": " Couleur ",
        "Front": " Avant ",
        "Back": " Après ",
        "Multi-function-Card": " Carte multifonction ",
        "Receiver-Card": " Carte de réception ",
        "Port": " Port ",
        "Background_Color": " Couleur de fond ",
        "Web_Window": " Fenêtre Web ",
        "Add_Single-Line_Text_Window": " Ajouter une seule ligne de fenêtre de texte ",
        "Add_Environment_Window": " Ajouter une fenêtre d'environnement ",
        "Environment_Window": " fenêtre d'environnement ",
        "Single-Line_Text_Window": " Fenêtre texte d'une seule ligne ",
        "Single-Line_Text": " Une seule ligne de texte ",
        "Add_Multi-Line_Text_Window": " Ajouter une fenêtre de texte multiligne ",
        "Multi_Text_Window": " Fenêtre Multi-texte ",
        "Multi-Line_Text_Window": " Fenêtre de texte multiligne ",
        "Multi_Text": " Texte multiligne ",
        "Add_Clock_Window": " Ajouter une fenêtre d'horloge ",
        "Clock_Window": " fenêtre d'horloge ",
        "Clock": " l'horloge ",
        "Add_web": " Ajouter web ",
        "Web": " web ",
        "No_Program": " Aucun programme ",
        /*网页窗*/
        "Length_of_1_-_5000": " Limite de 1 à 5000 caractères ",
        /* rss 窗 */
        "Length_of_1_-_5000": " Limite de 1 à 5000 caractères ",
        /*文件窗*/
        "Add_media_material": " Ajouter un fichier de matériau ",
        "Add_Material": " Ajouter du matériel ",
        "Empty": " Vide ",
        "Media_List": " matériel Liste ",
        "Play_Duration": " Durée de jeu ",
        "Play_Times": " temps de jeu ",
        "Keep_Aspect_Ratio": " Conserver les proportions ",
        "Random_Effect": " Effets aléatoires ",
        "You_can_adjust_the_play_layer_from_the_order_of_the_play_windows": " Vous pouvez ajuster le calque de lecture à partir de l'ordre des fenêtres de lecture ",
        "Multiple_content_pages_will_play_in_sequence": " Plusieurs pages de programme joueront dans l'ordre ",
        /* 同步播放窗 */
        "Sync_Program_Window": " Fenêtre du programme de synchronisation ",
        /*模拟时钟*/
        "Fixed_Text": " Texte fixe ",
        "Text": " Texte ",
        "Date": " Date ",
        "Week": " semaine ",
        "Anolog_Clock": " Horloge analogique ",
        "Digital_Clock": " Horloge digitale ",
        "Multi_Line_View": " Affichage multiligne ",
        "Single_Line_View": " Affichage simple ligne ",
        /*计时窗口*/
        "Add_Timing_Window": " Ajouter une fenêtre de chronométrage ",
        "Timing_Window": " Fenêtre de chronométrage ",
        "Timing": " Timing ",
        "Timer": " Timing positif ",
        "Countdown_Timer": " Compte à rebours ",
        "_**have_started": "** Déjà commencé",
        "To_**_there_are": " Pour ** il y a ",
        "Starting_Time": " Heure de début ",
        "Arrival_Time": " Heure d'arrivée ",
        /*天气窗口*/
        "Add_Weather_Window": " Ajouter une fenêtre météo ",
        "Weather_Window": " fenêtre météo ",
        "Weather": " météo ",
        "Bei_Jing": " Bei Jing ",
        "Chose_City": " Choisissez une ville ",
        "Loading_Wether_Info": " Chargement des informations météo ",
        "Load_Weather_Info_Success": " Informations météo chargées avec succès ",
        "Load_Weather_Info_Failure": " Informations météo chargées avec Échec ",
        "Please_Select_Contents": " Veuillez sélectionner le contenu ",
        "Weather_API_is_unavailable,Ask_for_server_administrator": " Weather API est temporairement indisponible, veuillez contacter l'administrateur du serveur ",
        "City_Name": " Nom de Ville ",
        "Select_City": " Sélectionnez une ville ",
        "Current_Temperature": " Température actuelle ",
        "Temperature": " Température ",
        "Receiver_Temperature": " Température de l'armoire ",
        "Temp": " Température ",
        "One_Day": " Un jour ",
        "Week": " semaine ",
        "Month": " Mois ",
        "Bit_Error_Rate": " Taux d'erreur binaire ",
        "Environment_Temperature,_Humidity,_Smoke_and_Brightness": " Température ambiante, humidité, fumée, carte de luminosité",
        "Wind": " Vent ",
        "Hum": " Hum ",
        "Current_Humidity": " Humidité actuelle ",
        "Humidity": " Humidité",
        "Receiver_Humidity": " Humidité de la boîte ",
        "Brightness": " La luminosité",
        "Volt": " Tension ",
        "Smoke": " Fumée ",
        "Smog": " Sans fumée ",
        "Noise": " Le bruit ",
        "Sender_Index": " Index de l'expéditeur ",
        "Upload_files_by_dragging_them_below": " Glisser-déposer le fichier de téléchargement ",
        "Receiver_Index": " Index du récepteur ",
        "Port": " Port ",
        "AQI": " AQI ",
        "Smoke": " Fumée ",
        "Dressing_Index": " Indice de pansement ",
        /* 警报阈值设置 */
        "Setting_items": "Élément de configuration ",
        "Enable": " Activer ",
        "Statement": " Description ",
        "Critical": " Critique ",
        "Warning": " Attention ",
        "Unit": " Unité",
        "Expand_All": " Développer tout ",
        "Collapse_All": "Pliant tout",
        "Upper_Receiver_Temperature": " Température du récepteur supérieure ",
        "Lower_Receiver_Temperature": " température du récepteur plus basse ",
        "Upper_Environment_Temperature": " Température ambiante supérieure ",
        "Lower_Environment_Temperature": " température ambiante inférieure ",
        "Receiver_Smoke": " Fumée du récepteur ",
        "Environment_Humidity": " Environnement Humidité",
        "Environment_Smoke": " Environnement Fumée ",
        "Minor_Alarm": " Alerte secondaire ",
        "Major_Alarm": " Alarme majeure ",
        "Critical_Alarm": " Alerte critique ",
        "Threshold": " Seuil ",
        "Enabled": " Activer ",
        "Reset": " Réinitialiser ",
        "Sending...": " Envoi...",
        "The_system_sends_an_alarm_message_when_the_[Bit_Error_Rate]_exceeds_the_threshold!":
            " Lorsque le taux d'erreur sur les bits dépasse le seuil, le système enverra un courrier électronique d'alerte!",
        "The_system_sends_an_alarm_message_when_the_[Receiver_Temperature]_exceeds_the_threshold!":
            " Lorsque la température de l'armoire est supérieure au seuil, le système enverra un courrier électronique d'alerte!",
        "The_system_sends_an_alarm_message_when_the_[Receiver_Temperature]_belows_the_threshold!":
            " Lorsque la température de l'armoire est inférieure au seuil, le système enverra un courrier électronique d'alerte!",
        "The_system_sends_an_alarm_message_when_the_[Receiver_Humidity]_exceeds_the_threshold!":
            " Lorsque l'humidité de l'armoire dépasse le seuil, le système envoie un courrier électronique d'alerte!",
        "The_system_sends_an_alarm_message_when_the_[Receiver_Smoke]_exceeds_the_threshold!":
            " Lorsque la fumée dépasse le seuil, le système enverra un courrier électronique d'alerte!",
        "The_system_sends_an_alarm_message_when_the_[Environment_Temperature]_exceeds_the_threshold!":
            " Lorsque la température ambiante est supérieure au seuil, le système enverra un courrier électronique d'alerte!",
        "The_system_sends_an_alarm_message_when_the_[Environment_Temperature]_belows_the_threshold!":
            " Lorsque la température ambiante est inférieure au seuil, le système enverra un e-mail d'alerte!",
        "The_system_sends_an_alarm_message_when_the_[Environment_Humidity]_exceeds_the_threshold!":
            " Lorsque le taux d'humidité ambiante dépasse le seuil, le système enverra un courrier électronique d'alerte!",
        "The_system_sends_an_alarm_message_when_the_[Environment_Smoke]_exceeds_the_threshold!":
            " Lorsque la fumée ambiante dépasse le seuil, le système enverra un e-mail d'alerte!",
        "The_threshold_must_be_an_integer_!": " Le seuil doit être un entier ",
        "The_threshold_exceeds_the_allowable_range_!": " Le seuil dépasse la plage autorisée ",
        "Illegal_value_!": " Valeur illégale ",
        "When_setting_upper_temperature_alarm,_critical_threshold_must_be_greater_than_Lower_Receiver_Temperature's_warning_threshold_!":
            " Lors du réglage d'une alarme de haute température, le seuil critique doit être supérieur au seuil normal de basse température de l'armoire!",
        "When_setting_upper_temperature_alarm,_warning_threshold_must_be_greater_than_Lower_Receiver_Temperature's_warning_threshold_!":
            " Lors du réglage d'une alarme de température élevée, le seuil normal doit être supérieur au seuil normal de la température basse de l'armoire!",
        "When_setting_lower_temperature_alarm,_critical_threshold_must_be_less_than_Upper_Receiver_Temperature's_warning_threshold_!":
            " Lors du réglage d'une alarme de basse température, le seuil critique doit être inférieur au seuil normal pour la température élevée de l'armoire!",
        "When_setting_lower_temperature_alarm,_warning_threshold_must_be_less_than_Upper_Receiver_Temperature's_warning_threshold_!":
            " Lors du réglage d'une alarme de basse température, le seuil normal doit être inférieur au seuil normal pour la température élevée de l'armoire!",
        "When_setting_upper_temperature_alarm,_critical_threshold_must_be_greater_than_Lower_Environment_Temperature's_warning_threshold_!":
            " Lors du réglage d'une alarme de température élevée, le seuil critique doit être supérieur au seuil normal de basses températures ambiantes!",
        "When_setting_upper_temperature_alarm,_warning_threshold_must_be_greater_than_Lower_Environment_Temperature's_warning_threshold_!":
            " Lors du réglage d'une alarme de température élevée, le seuil normal doit être supérieur au seuil normal de température ambiante basse!",
        "When_setting_lower_temperature_alarm,_critical_threshold_must_be_less_than_Upper_Environment_Temperature's_warning_threshold_!":
            " Lors du réglage d'une alarme de basse température, le seuil critique doit être inférieur au seuil normal pour les températures ambiantes élevées!",
        "When_setting_lower_temperature_alarm,_warning_threshold_must_be_less_than_Upper_Environment_Temperature's_warning_threshold_!":
            " Lors du réglage d'une alarme de basse température, le seuil normal doit être inférieur au seuil normal de température ambiante élevée!",
        "Critical_threshold_must_be_greater_than_warning_threshold_when_setting_upper_temperature_alarm_!":
            " Lors du réglage d'une alarme de température élevée, le seuil critique doit être supérieur au seuil normal!",
        "Critical_threshold_must_be_less_than_warning_threshold_when_setting_lower_temperature_alarm_!":
            " Lors du réglage d'une alarme de basse température, le seuil critique doit être inférieur au seuil normal!",
        "Upper_temperature_alarm's_lowest_threshold_must_be_greater_than_lower_temperature's_highest_threshold_!":
            " La valeur minimale pour le réglage de l'alarme de température élevée doit être supérieure à la valeur la plus élevée pour le réglage de l'alarme de température basse!",
        "Lower_temperature_alarm's_highest_threshold_must_be_less_than_upper_temperature's_lowest_threshold_!":
            " La valeur la plus élevée du paramètre d'alarme de température basse doit être inférieure à la valeur la plus basse définie par l'alarme de température haute!",
        "Alarm_Settings": " Paramètres d'alerte ",
        "Mail cannot be empty": " Le courrier ne peut pas être vide ",
        "Failed_to_load_alarm_setting_information": "Obtenir des informations de configuration d'alerte avec Échec ",
        "Please_try_again_later_or_contact_administrator": " Veuillez réessayer ultérieurement ou contacter l'administrateur",
        "Please_select_a_device_first": " Veuillez d'abord sélectionner un terminal ",
        "All_thresholds_will_be_set_to_0_and_all_unit_is_restored_to_its_default_value,_all_settings_will_be_unavailable_also.":
            " Tous les seuils seront réglés sur 0, l'unité reviendra à la valeur par défaut et tous les paramètres seront désactivés.",
        "All_thresholds_and_units_is_reseted_to_its_default_value,_all_settings_will_be_unavailable_also.":
            " Tous les seuils et les unités seront réinitialisés aux valeurs par défaut et tous les paramètres seront désactivés",
        "Continue_to_reset_it?": " Continuer à réinitialiser?",
        "Alarm_set_successfully": " L'alerte est définie avec succès ",
        "Alarm_setting_failed": " Le réglage de l'alerte a échoué",
        /*服务器节目列表*/
        "Server_Content_List": " Liste de programme du serveur ",
        "Create_Time": " Heure de création ",
        "Specific_Creating_Time": " Limiter le temps de création ",
        "Last_Edition": " Dernière fois édité",
        "Publish_the_content": " Publier le contenu ",
        "Published_To": " Envoyé à",
        "Publish_the_content": " Publier le contenu ",
        "Select_A_Template": " Veuillez sélectionner un modèle ",
        "Publish_": " Publier ",
        "Publishing_Progress": " Publishing Progress ",
        "Contents_Materials": " Ressources du contenu ",
        "NO_Material": " Pas de ressources ",
        "Viewing_materials": " Afficher les ressources ",
        "Delete_Contents": " Supprimer le contenu ",
        "A_New_Failed,A_Terminal_With_The_Name_Has_Already_Exists": " Un nouveau échec, un terminal avec le nom a déjà existé",
        "A_Edit_Failed,A_Terminal_With_The_Name_Has_Already_Exists": " Un l'édition échec, un terminal avec le nom a déjà existé",
        "Delete_Failed,The_User_In_Terminal_Group_Is_Not_Empty": " La suppression échoue. L'utilisateur du groupe de terminaux n'est pas vide ",
        "Delete_Failed,The_LED_In_Terminal_Group_Is_Not_Empty": " La suppression a échoué, le voyant situé sous le groupe de terminaux n'est pas vide ",
        "Delete_Failed,The_Child_Terminal_In_Terminal_Group_Is_Not_Empty": " La suppression échoue.Le groupe de sous-terminaux du groupe de terminaux n'est pas vide ",
        "Delete_Failed,The_LED_Is_Not_Empty": " La suppression a échoué, le voyant n'est pas vide ",
        "Publish_Contents": " Publier le contenu ",
        "Edit_Contents": " Modifier le contenu ",
        "Content_Info": " contenu Informations ",
        "Content_Size": " contenu Taille ",
        "Author": " Auteur ",
        "Limit_Author": " Restreindre l'auteur ",
        "If_Report_Gps": " Si Signaler Gps ",
        "Status": " Etat",
        "Terminal_Status": "État du terminal ",
        "All": " Tous ",
        "Publish": " Publié",
        "Report": " Rapport ",
        "Location_Name": " Nom de la localisation ",
        "Location_Group": " Groupe de localisation ",
        "Pending": " En attente d'examen ",
        "Report_Interval": " Intervalle de rapport ",
        "Interval": " Intervalle ",
        "Refresh_Interval": " Intervalle de rafraîchissement ",
        "Minimum_is_60": " La valeur minimale est 60",
        "Template": " Modèle ",
        "Search_Contents_Name": " Rechercher le nom du contenu ",
        "Display_format_is_player_locale_dependent": " Le format d'affichage dépend des paramètres régionaux du lecteur ",
        "Create_Date": " Date de création ",
        "All_Terminals": " Tous les terminaux ",
        "Click_Publish_to_publish_program": " Cliquez sur Publier pour publier le contenu ",
        "Template_can_not_be_published": " Le modèle ne peut pas être publié",
        "You_have_no_permission_to_publish_the_contents_directly,_it_is_pending": " Le programme doit être révisé par l'administrateur. Vous n'avez pas la permission de poster directement ",
        "Your_content_is_invalid,_check_up!": " Votre contenu est invalide, s'il vous plaît vérifier!",
        "Invalid_content,_please_check!": " contenu invalide, s'il vous plaît vérifier!",
        "Up_to_4_pages_supported!": " Supporte jusqu'à 4 pages!",
        "Up_to_4_file_windows_supported!": " Supporte jusqu'à 4 fenêtres de lecture de fichiers!",
        "Audit_materials": " Revoir le matériel ",
        "Approved": " Approuvé",
        /*操作日志*/
        "Operation_Log": " Journal d'opération ",
        "Select_Terminal": " Sélectionnez terminal ",
        "Select_a_terminal": " Sélectionnez un terminal ",
        "No_Log": " Non bûche ",
        "Add_Log": "S'il vous plaît ajouter bûche ",
        "Address": " Adresse ",
        "Index": " Indice ",
        "Operation": " Opération ",
        "Operator": " Opérateur ",
        "Specific_Operator": " Restreindre opérateur ",
        "Operation_Date": " Temps de Opération ",
        "Limit_Operation_Date": " Restreindre Temps de Opération ",
        "Content": " Contenu ",
        "Update_Contents": " Mettre à jour le contenu ",
        "Switch_Contents": " Changer le contenu ",
        "Play_Program": " Jouer un programme ",
        "Play_New_Program": " Jouer un nouveau spectacle ",
        "Start_Play": " Commencer à jouer ",
        "Start_Play_Program": " Commencez à jouer le spectacle ",
        "Delete_Contents": " Supprimer le contenu ",
        /*终端日志*/
        "Terminal_Log": " terminal Bûche ",
        "Log_Level": " Bûche Niveau ",
        "Log_Type": " Bûche Classification",
        "Log_Description": " Bûche Description ",
        "Item_Title": " Titre de l'article ",
        "Item_Description": " Description de l'article ",
        "Update_Interval": " Intervalle de mise à jour ",
        "Speed": " La vitesse ",
        "S": "S",
        "Px": " Px ",
        "Log_Info": " Bûche Les informations",
        "Other_Info": " Autres informations ",
        /*地图监控*/
        "Monitoring": "Surveillance",
        "Terminal_Monitoring": " Terminal Surveillance ",
        "Environment": " Environnement ",
        "Map_Monitoring": "Carte Surveillance ",
        "Add_terminal_to_here": " Ajouter un terminal ici",
        "Select_a_terminal_to_here": " Sélectionnez un terminal ici ",
        /*安全控制*/
        "Security_Control": " Contrôle de sécurité",
        "Blocked_IP_List": " Liste IP bloquée",
        "Unblock": " Lever l'interdiction ",
        "Block_Time": " Temps interdit ",
        "Block_Account": " Compte banni ",
        "Block_Times": " Nombre d'interdictions ",
        "Times": " Nombre de fois ",
        "Blocked": " Bloqué",
        "UnBlocked": " Débloqué",
        "Download_ChromeAPP": " Télécharger ChromeAPP ",
        /*定时指令管理*/
        "Schedule": " Programme ",
        "Schedule_": " Programme ",
        "Schedule_Command": "Instruction Programme ",
        "Schedule_Contents": " Contenu Programme ",
        "Command": " Instruction ",
        "Priority_": " Priorité",
        "Execution_Time": " Temps d'exécution ",
        "Valid_Date": " Date effective ",
        "Valid_Week": " Semaine effective ",
        "Value": " valeur ",
        "Add": " Ajouter ",
        "Sorting": " Le tri ",
        "Calender_View": " Calendrier Voir",
        "Calender": " Calendrier ",
        "List": " liste ",
        "When_multi_contents_shedule_time_repeat": " Lorsque plusieurs programmes sont répétés ",
        "Rotation_Mode": " Rotation Mode ",
        "Spot_Mode": " Spot Mode",
        "Spare_Mode": " réserve Mode ",
        "Rotation_": " Rotation ",
        "Spot_": " Spot ",
        "Spare_": " réserve ",
        "Bottom12212_": " Les programmes sont lus à tour de rôle et l'ordre de rotation du programme est trié par priorité",
        "Everyday": " Tous les jours ",
        "Duration_of_Everyday": " Durée de tous les jours ",
        "Duration": " Durée ",
        "Duration_statistics": " Statistiques de durée ",
        "Programs_statistics": " Statistiques des programmes ",
        "Whole_day": " Toute la journée ",
        "This_group_have_no_contents_schedule": " Il n'y a pas de programme pour ce groupe ",
        "No_Contents_Schedule": " Pas de contenu Horaire ",
        "This_group_have_no_command_schedule": " Ce groupe n'a pas Instruction Programme ",
        "No_Command_Schedule": " Pas de Commander Horaire ",
        "At_any_specific_time,_there_is_only_one_play_mode.The_priority_level_is": " Un seul type de programme sera diffusé à la fois. La priorité est ",
        "All_the_rotation_contents_on_the_list_will_play_in_turn,_on_the_premise_that_there_is_no_spot_content_at_the_same_time": " S'il n'y a pas de programme interstitiel dans la même période, tous les carrousels seront joués à tour de rôle en fonction de la priorité",
        "When_there_is_a_spot_content_coexisting_with_others,_only_the_spot_content_will_play._Moreover,_when_multiple_spot_contents_coexist,_the_one_in_the_front_rank_will_play": " Lorsqu'il y a un programme entrelacé dans la même période, la période sélectionnera l'un des programmes entrelacés de priorité la plus élevée ",
        "The_spare_content_in_the_front_rank/on_the_top_of_the_priority_list_will_cover_the_rest,_on_the_premise_that_neither_spot_nor_rotation_contents_exist_at_the_same_time": " Lorsqu'il n'y a ni programme de plug-in ni programme de carrousel dans la même période, la période sélectionnée sélectionne un programme de rembourrage avec la priorité la plus élevée à jouer. ",
        "Add": " Ajouter ",
        "New_Scheduled_Command_Item": " Nouvel élément de commande programmé",
        "Edit_Scheduled_Command_Item": " Éditer élément de commande programmé",
        "New_Scheduled_Contents_Item": " Nouvel élément de Nouvel élément de commande programmé programmé",
        "Edit_Scheduled_Contents_Item": " Éditer élément de Nouvel élément de commande programmé programmé",
        "No_items_match_your_search": " Aucun article ne correspond à votre recherche ",
        "Specific_Date": " Date spécifiée ",
        "Specific_Week": " Semaine désignée ",
        "Specific_Time": " Temps spécifié",
        "Only_C6_have_the_function": " Seul C6 a cette fonctionnalité",
        "Only_C6,C7,C8_have_the_function": " Seuls les C6, C7 et C8 ont cette fonction ",
        "No_Limit": " Sans limite ",
        "Limit": " limite ",
        "From": "À partir de ",
        "Until": "À",
        "Prefix": " Avant ",
        "Suffix": " Après ",
        "Please_select_the_date": " S'il vous plaît sélectionner une date ",
        "Monday": " Le lundi ",
        "Tuesday": " Mardi ",
        "Wednesday": " Le mercredi ",
        "Thursday": " Jeudi ",
        "Friday": " Vendredi ",
        "Saturday": " Samedi ",
        "Sunday": " Le dimanche ",
        "Play_Length": " Durée du programme ",
        "Delete_All_Contents": " Effacer tous les spectacles ",
        "Clear_Cache_Files": " Effacer le fichier cache ",
        "Select_Contents": " S'il vous plaît sélectionner un spectacle ",
        "Apply_to_Subgroup": " Appliquer aux sous-groupes en même temps ",
        "How_to_set_scheduled_command": " Comment définir les instructions de chronométrage ",
        "Select_a_group_to_set_its_schedule": " Vous pouvez sélectionner un groupe de terminaux pour définir la planification de ce groupe. ",
        "Terminal_will_apply_the_schedule_of_its_group": " Le terminal appliquera la planification du groupe auquel il appartient ",
        "If_teminal_did_not_have_the_contents_in_scheduled_contents": " Si le terminal n'a pas de programme dans la planification de programme ",
        "it_will_download_automatically": " Le terminal téléchargera automatiquement le programme ",
        "and_the_scheduleed_contents_item_of_contens_come_into_force_after_finishing": " L'élément de planification de programme prend effet une fois le téléchargement terminé",
        "You_can_cancel_schedule_by_emptying_schedule_items": " Vous pouvez annuler le réglage du programme en effaçant le programme ",
        "Enter_execution_time": " S'il vous plaît entrer le temps d'exécution ",
        "Enter_Specific_Date": " S'il vous plaît entrer une date qualifiée ",
        "Schedule_modification_not_applied, still_leave_this_page?": " L’horaire a été modifié mais n’a pas été soumis. Vous quittez cette page?",
        "Program_modification_not_applied, still_leave_this_page?": " Le programme a été modifié mais n'a pas été envoyé. Vous quittez cette page?",
        "Schedule_added_but_not_applied, still_leave_this_page?": " L'horaire a été ajouté mais n'a pas été envoyé. Vous quittez cette page?",

        "Language": " Langue ",
        "Sign_up_is_not_open_to_public": " Pas encore ouvert pour l'inscription ",
        "Product": " Produit ",
        "Solution": " Scheme ",
        "Case": " Affaire ",
        "Change_Password": " Changer le mot de passe ",
        "Change_password_succeed": " Changer le mot de passe avec succès ",
        "Change_password_failed,_check_the_old_password": "Échec du changement du mot de passe, veuillez vérifier l'ancien mot de passe ",
        "Sign_Up_Failed": " L'enregistrement a échoué",
        "Old_Password": " Ancien mot de passe ",
        "New_Password": " Nouveau mot de passe ",
        "Remember_Password": " Mémoriser le mot de passe ",
        "Forgot_Password": " Mot de passe oublié",
        "characters_left": " Mots restants ",
        "Move_Up": " Mouvement ascendant continu ",
        "Colorlight_Cloud_Center": " Colorlight Cloud Platform ",
        "Terminal_Version": " Version du terminal ",
        "Set_Report_Time": " Définir l'intervalle ",
        // 重置密码
        "Reset_Password": " Réinitialiser le mot de passe ",
        "Please_enter_new_password": " S'il vous plaît entrer un nouveau mot de passe ",
        "Please_enter_password_again": " S'il vous plaît entrer un nouveau mot de passe ",
        "Password_contains_illegal_characters": " Le mot de passe contient des caractères illégaux ",
        "Must_contain_numbers,_uppercase_and_lowercase_letters": " Doit contenir des chiffres et des lettres majuscules et minuscules ",
        "Reset_password_success!": " Réinitialiser le mot de passe avec succès!",
        "Reset_password_failed!": " Réinitialiser le mot de passe avec Échec!",
        "At_least_8_or_more_characters": " Au moins huit personnages ",
        "The_two_passwords_you_entered_did_not_match": " Mot de passe incohérent entré deux fois ",
    });
}]);
